name: flutter_gemini
description: "Google Gemini chat Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.1
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:


   fonts:
     - family: Roboto
       fonts:
        - asset: fonts/roboto/RobotoMono-Regular.ttf
        - asset: fonts/roboto/RobotoMono-Bold.ttf
     - family: Santello
       fonts:
        - asset: fonts/santello/SANTELLO.ttf

   uses-material-design: true

